import 'package:backend/src/auth/auth_middleware.dart';
import 'package:dart_frog/dart_frog.dart';

/// Progress needs a session, like everything else that is about someone's own
/// work.
///
/// Not rate limited, unlike `/projects`: that limiter guards outbound work —
/// git clones and registry traffic — and this endpoint does none. It reads one
/// map entry, and a client watching a scan is expected to ask every second or
/// two for as long as the scan runs.
///
/// The scan id is a capability: whoever holds it can read that scan's counts.
/// It is generated by the client and never listed anywhere, and what it
/// discloses is how many packages a repository has and how far along a scan is
/// — no names, no versions, no findings.
Handler middleware(Handler handler) => handler.use(requireAuth());
